Ttag
baza-trainee/baza-crm-backend pull request #5
Opened 2024-05-25 17:37 UTC by pavloruban1

add tag

2024-05-25 18:04 UTC, Simkav requested changes

2024-05-25 18:04 UTC, Simkav commented on server/src/app.ts
> +import tagRouter from './tag/tag.router';
remove

2024-05-25 18:04 UTC, Simkav commented on server/src/app.ts
> +app.use('/api', tagRouter);
remove

2024-05-25 18:04 UTC, Simkav commented on server/src/tag/tag.entity.ts
> +    technologies!: User[];
remove

2024-05-25 18:04 UTC, Simkav commented on server/src/tag/tag.entity.ts
> +    is_specialization!: boolean;
isSpecialization

2024-05-25 18:04 UTC, Simkav commented on server/src/tag/tag.router.ts
> +
remove /tags from all routes, leave only in export

2024-05-25 18:04 UTC, Simkav commented on server/src/user/user.entity.ts
> +  tags!: Tag[];
remove

2024-05-25 18:04 UTC, Simkav commented on server/src/tag/tag.service.ts
> +  const user = await userRepository.findOne({ where: { id: userId }, relations: ['tags'] });
findUserByIdWithTags in user service?

2024-05-25 18:04 UTC, Simkav commented on server/src/tag/tag.controller.ts
> +  const { userId, tagId } = req.body;
userId from jwt token not from body

2024-05-25 18:04 UTC, Simkav commented on server/src/tag/tag.schemas.ts
> +export const createTagSchema = Joi.object({
isSpecialization?

2024-05-25 18:04 UTC, Simkav commented on server/src/tag/tag.service.ts
> +  const tag = tagRepository.create({ name });
see how created user in user service

2024-05-25 18:04 UTC, Simkav commented on server/src/tag/tag.router.ts
> +tagRouter.put(
put=>patch

2024-05-25 19:24 UTC, pavloruban1 commented on server/src/app.ts
> +import tagRouter from './tag/tag.router';
fix

2024-05-26 09:06 UTC, Simkav commented on server/src/tag/tag.service.ts
> +};
https://github.com/baza-trainee/baza-crm-backend/pull/5/files#r1614791924

2024-05-27 09:31 UTC, merged